### ISSUE TITLE
Dropdown menu does not close

### ISSUE THREAD

**Issue by vincentf123** [Leberkasrechner/Leberkasrechner#7]
![image](https://github.com/Leberkasrechner/Leberkasrechner/assets/147273663/148427c5-4c0f-40bc-b3a6-c4840fa9702f)

The dropdown menu does not close when clicking on the X

**Comment by Phipsiart** [comment]
We are currently investigating this issue. Thanks for your patience

**Comment by da-ssl** [comment]
We are working tirelessly on a solution to this problem

**Comment by da-ssl** [comment]
@Phipsiart @vincentf123 the issue is now **fixed**; it was caused by a double integration of bootstrap. 

Unfortunately, the animation is not completely flawless yet (the top margin of the navbar head items is reducing when the navbar is expanded), but that is no urgent problem and probably be fixed soon
